server:
  port: 8082
databases:
  - user: admin
    password: 12345
    host: localhost
    dbName: shopDev
  - user: user
    password: 54321
    host: localhost
    dbName: shopUser
security:
  jwt:
    key: abc123