server:
  port: 8082
  mode: dev
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  dbname: shopdevgo
  maxIdleConns: 10  # Max connects idle are allowed to be kept in the pool
  maxOpenConns: 100 # Max connects are allowed to be opened
  connMaxLifetime: 3600 # Max life time of a connection in seconds 
logger:
  logLevel: debug
  fileLogName: "./storages/logs/dev.001.log"
  maxSize: 500 
  maxBackups: 3
  maxAge: 28
  compress: true
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  database: 0